apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: devsecops-wordpress
spec:
  selector:
    app.kubernetes.io/name: wordpress
  ports:
    - name: http
      port: 80
      targetPort: http
